/**
 * Localization for the openpublictransport card.
 * Uses hass.language to select the right strings.
 */

const translations: Record<string, Record<string, string>> = {
  en: {
    now: "now",
    in_min: "in {min} min",
    in_1_min: "in 1 min",
    no_departures: "No departures available",
    no_trip_data: "No trip data available",
    entity_unavailable: "Entity is unavailable",
    please_define_entity: "Please define an entity",
    alternative_connections: "Alternative Connections",
    connection_at_risk: "Connection at risk",
    risk: "risk",
    transfer: "Transfer",
    transfers: "transfers",
    platform: "Pl.",
    time: "Time",
    line: "Line",
    destination: "Destination",
    track: "Track",
    table_layout: "Table (Departure Board)",
    compact_layout: "Compact (Chips)",
    trip_layout: "Trip (Journey)",
    entity: "Entity",
    layout: "Layout",
    theme: "Theme",
    max_departures: "Max Departures",
    show_header: "Show Header",
    show_platform: "Show Platform",
    show_delay: "Show Delay",
    show_realtime: "Show Realtime Indicator",
    display_options: "Display Options",
  },
  de: {
    now: "jetzt",
    in_min: "in {min} min",
    in_1_min: "in 1 min",
    no_departures: "Keine Abfahrten verfügbar",
    no_trip_data: "Keine Verbindungsdaten verfügbar",
    entity_unavailable: "Entity nicht verfügbar",
    please_define_entity: "Bitte eine Entity auswählen",
    alternative_connections: "Alternative Verbindungen",
    connection_at_risk: "Anschluss gefährdet",
    risk: "Risiko",
    transfer: "Umstieg",
    transfers: "Umstiege",
    platform: "Gl.",
    time: "Zeit",
    line: "Linie",
    destination: "Ziel",
    track: "Gleis",
    table_layout: "Tabelle (Abfahrtstafel)",
    compact_layout: "Kompakt (Chips)",
    trip_layout: "Verbindung (Trip)",
    entity: "Entity",
    layout: "Layout",
    theme: "Design",
    max_departures: "Max. Abfahrten",
    show_header: "Kopfzeile anzeigen",
    show_platform: "Gleis anzeigen",
    show_delay: "Verspätung anzeigen",
    show_realtime: "Echtzeit-Indikator anzeigen",
    display_options: "Anzeigeoptionen",
  },
  fr: {
    now: "maintenant",
    in_min: "dans {min} min",
    in_1_min: "dans 1 min",
    no_departures: "Aucun départ disponible",
    no_trip_data: "Aucune donnée de trajet disponible",
    entity_unavailable: "Entité indisponible",
    please_define_entity: "Veuillez sélectionner une entité",
    alternative_connections: "Correspondances alternatives",
    connection_at_risk: "Correspondance menacée",
    risk: "risque",
    transfer: "Correspondance",
    transfers: "correspondances",
    platform: "Voie",
    time: "Heure",
    line: "Ligne",
    destination: "Destination",
    track: "Voie",
    table_layout: "Tableau (Panneau de départs)",
    compact_layout: "Compact (Puces)",
    trip_layout: "Trajet (Itinéraire)",
    entity: "Entité",
    layout: "Disposition",
    theme: "Thème",
    max_departures: "Départs max.",
    show_header: "Afficher l'en-tête",
    show_platform: "Afficher la voie",
    show_delay: "Afficher le retard",
    show_realtime: "Afficher l'indicateur temps réel",
    display_options: "Options d'affichage",
  },
  nl: {
    now: "nu",
    in_min: "over {min} min",
    in_1_min: "over 1 min",
    no_departures: "Geen vertrekken beschikbaar",
    no_trip_data: "Geen reisgegevens beschikbaar",
    entity_unavailable: "Entity niet beschikbaar",
    please_define_entity: "Selecteer een entity",
    alternative_connections: "Alternatieve verbindingen",
    connection_at_risk: "Aansluiting in gevaar",
    risk: "risico",
    transfer: "Overstap",
    transfers: "overstappen",
    platform: "Spoor",
    time: "Tijd",
    line: "Lijn",
    destination: "Bestemming",
    track: "Spoor",
    table_layout: "Tabel (Vertrekbord)",
    compact_layout: "Compact (Chips)",
    trip_layout: "Reis (Route)",
    entity: "Entity",
    layout: "Layout",
    theme: "Thema",
    max_departures: "Max. vertrekken",
    show_header: "Koptekst tonen",
    show_platform: "Spoor tonen",
    show_delay: "Vertraging tonen",
    show_realtime: "Realtime-indicator tonen",
    display_options: "Weergaveopties",
  },
  sv: {
    now: "nu",
    in_min: "om {min} min",
    in_1_min: "om 1 min",
    no_departures: "Inga avgångar tillgängliga",
    no_trip_data: "Inga resedata tillgängliga",
    entity_unavailable: "Entitet otillgänglig",
    please_define_entity: "Välj en entitet",
    alternative_connections: "Alternativa förbindelser",
    connection_at_risk: "Anslutning hotad",
    risk: "risk",
    transfer: "Byte",
    transfers: "byten",
    platform: "Spår",
    time: "Tid",
    line: "Linje",
    destination: "Destination",
    track: "Spår",
    table_layout: "Tabell (Avgångstavla)",
    compact_layout: "Kompakt (Chips)",
    trip_layout: "Resa (Rutt)",
    entity: "Entitet",
    layout: "Layout",
    theme: "Tema",
    max_departures: "Max avgångar",
    show_header: "Visa rubrik",
    show_platform: "Visa spår",
    show_delay: "Visa försening",
    show_realtime: "Visa realtidsindikator",
    display_options: "Visningsalternativ",
  },
  pl: {
    now: "teraz",
    in_min: "za {min} min",
    in_1_min: "za 1 min",
    no_departures: "Brak dostępnych odjazdów",
    no_trip_data: "Brak danych o podróży",
    entity_unavailable: "Encja niedostępna",
    please_define_entity: "Wybierz encję",
    alternative_connections: "Alternatywne połączenia",
    connection_at_risk: "Połączenie zagrożone",
    risk: "ryzyko",
    transfer: "Przesiadka",
    transfers: "przesiadki",
    platform: "Peron",
    time: "Czas",
    line: "Linia",
    destination: "Kierunek",
    track: "Tor",
    table_layout: "Tabela (Tablica odjazdów)",
    compact_layout: "Kompaktowy (Chipy)",
    trip_layout: "Podróż (Trasa)",
    entity: "Encja",
    layout: "Układ",
    theme: "Motyw",
    max_departures: "Maks. odjazdów",
    show_header: "Pokaż nagłówek",
    show_platform: "Pokaż peron",
    show_delay: "Pokaż opóźnienie",
    show_realtime: "Pokaż wskaźnik czasu rzeczywistego",
    display_options: "Opcje wyświetlania",
  },
  it: {
    now: "adesso",
    in_min: "tra {min} min",
    in_1_min: "tra 1 min",
    no_departures: "Nessuna partenza disponibile",
    no_trip_data: "Nessun dato di viaggio disponibile",
    entity_unavailable: "Entità non disponibile",
    please_define_entity: "Seleziona un'entità",
    alternative_connections: "Connessioni alternative",
    connection_at_risk: "Connessione a rischio",
    risk: "rischio",
    transfer: "Cambio",
    transfers: "cambi",
    platform: "Bin.",
    time: "Orario",
    line: "Linea",
    destination: "Destinazione",
    track: "Binario",
    table_layout: "Tabella (Pannello partenze)",
    compact_layout: "Compatto (Chip)",
    trip_layout: "Viaggio (Percorso)",
    entity: "Entità",
    layout: "Layout",
    theme: "Tema",
    max_departures: "Max. partenze",
    show_header: "Mostra intestazione",
    show_platform: "Mostra binario",
    show_delay: "Mostra ritardo",
    show_realtime: "Mostra indicatore tempo reale",
    display_options: "Opzioni di visualizzazione",
  },
};

export function localize(lang: string, key: string, params?: Record<string, string | number>): string {
  const langCode = lang?.substring(0, 2).toLowerCase() || "en";
  const strings = translations[langCode] || translations["en"];
  let text = strings[key] || translations["en"][key] || key;

  if (params) {
    for (const [k, v] of Object.entries(params)) {
      text = text.replace(`{${k}}`, String(v));
    }
  }

  return text;
}
